name = "ControlDashboard"
uuid = "ae05914c-be31-4945-8af2-1a58064b4257"
authors = ["Mitchell D Scott <scott.mitchell913@gmail.com>"]
version = "0.1.0"

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Coverage = "1.7.0"
Dash = "1.5.0"
DataFrames = "1.8.0"
DifferentialEquations = "7.16.1"
JuliaFormatter = "2.1.6"
OrdinaryDiffEq = "6.103.0"
PlotlyJS = "0.18.17"
SciMLBase = "2.124.0"
StaticArrays = "1.9.15"
Test = "1.10.10"
